spring:
  profiles:
    active: private
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.show_sql: true
      hibernate.format_sql: true
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate:
        default_batch_fetch_size: 100
  graphql:
    graphiql:
      enabled: true

graphql:
  servlet:
    enabled: true
    mapping: /graphql
    corsEnabled: true
    cors:
      allowed-origins: "*"
      allowed-methods: GET, HEAD, POST, PATCH
    exception-handlers-enabled: true
    context-setting: PER_REQUEST_WITH_INSTRUMENTATION
    async-mode-enabled: true
  tools:
    schema-location-pattern: "**/*.graphqls"
    introspection-enabled: true

http.cors.enabled: true
http.cors.allow-origin: "*"